project:
  type: book

book:
  title: "BoekQuarto"
  author: "Harrie Jonkman (opmaak)"
  date: "5-9-2022"
  chapters:
    - index.qmd
    - 00-inl.qmd
    - 01-ant.qmd
    - 02-opl.qmd
    - 03-werk.qmd
    - 04-zorg.qmd
    - 05-zorgjeugd.qmd
    - 06-gez.qmd
    - 07-crim.qmd
    - 08-conc.qmd
    - references.qmd

bibliography: DHlit.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

